version: '3.9'

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    command: server /data --console-address ":9001"

  backend:
    build: ./back
    container_name: backend
    ports:
      - "8080:8080"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb myminio/docs;
      /usr/bin/mc policy set public myminio/docs;
      /usr/bin/mc admin bucket remote set myminio/docs /config/cors.json;
      exit 0;
      "
    volumes:
      - ./cors.json:/config/cors.json